### PR TITLE
Assorted Autocomplete Fixes & Improvements

### LINKED ISSUE #1272: "XML Parsing Error: not well-formed" when using Carrier autocomplete
For some reason, typing in `b` or `B` results into the Carrier box when adding a new flight results in

```
XML Parsing Error: not well-formed
Location: https://openflights/
Line Number 1, Column 64:
```

### LINKED ISSUE #1283: Multi-input autocomplete popup size improvement
The multi-flight input has this feature (?) where the number of autocomplete results is reduced with each successive row.

The first row gets up to 6 suggestions, the second up to 5, ...

Relevant comment from `autocomplete.php`:

```
// Limit the number of rows returned in multi-input, where space is at a premium
```

This is done because the text fields are at the bottom of the screen.

But instead of doing all this work (this limits are worked out in a really funny way and passed all the way to the database), we could just pop the autocomplete window *above* the entry.

### PR DESCRIPTION
**Pull request by chrisrosset**
- Autocomplete display improvement for multi-input flight mode. Instead of decreasing the number of suggestions to control the size of the popup, we show it above the entry field. Fixes #1283.
- Fixed parameter encoding issues on the way to the server.
- Changed the parameter scheme for the endpoint to reduce coupling. The server no longer cares about the `id` of the `input` the search is for - it only cares about the type (airlines, airports, planes, mixed aka multisearch). Closes #1269.
- Converted server responses to JSON (fixes #1272).
- General refactoring of `autocomplete.php` to improve naming, fix warnings, simplify flow, etc.
- Moved some presentation logic to the UI.

I would love to remove the last autocomplete requests from `xmlHttpPost`... Those aren't really autocomplete as much as matching airline/airport codes and would probably be better done by making requests to the airport/airline search APIs but those are not that great either right now so I've just patched things for now. This behavior only happens when you tab out of the entry fields - but not if you change focus with the mouse... Would be great to remove that but then you'd have to "type, enter, tab" instead of "type, tab"... but maybe it's not that big of a deal?

### CODE REVIEW

**Comment by chrisrosset** [comment]
@reedy would be nice if this could go ahead #1271.

File: openflights.js [hunk 1]
```diff
@@ -926,7 +957,15 @@ function xmlhttpPost(strURL, id, param) {
...
-        var cols = self.xmlHttpReq.responseText.split(";");
+        const resp = JSON.parse(self.xmlHttpReq.responseText);
+        var cols;
+        // Hack the old format back in (for now)
+        if (resp.length) {
+          cols = [resp[0].value, resp[0].label];
+        } else {
+          cols = [""];
+        }
+        console.log("cols", cols);
```
Comment (reedy) [inline openflights.js]: debug call

**Comment by reedy** [comment]
Seems to work fine, and definitely fixes the various referenced fixed issues.

There's one `console.log()` left behind that was causing browser console spam

File: openflights.js (hunk 1 above)
Comment (chrisrosset) [reply openflights.js]: removed

File: openflights.css [hunk 2]
```diff
@@ -207,6 +207,14 @@ td.donate2 {
 }
 
 /* Autocomplete styles */
+.autocomplete {
+ /* TODO: improve this in code review
```
Comment (chrisrosset) [inline openflights.css]: @reedy Is there a better way to do this?

**Comment by reedy** [comment]
I'm going to ask a silly question...

Where is the multi flight input? Is that part of the import?

**Comment by reedy** [comment]
> Where is the multi flight input? Is that part of the import?

The "more" button on the basic screen... something I've never used

**Comment by chrisrosset** [comment]
> > Where is the multi flight input? Is that part of the import?
> 
> The "more" button on the basic screen... something I've never used

The live version (at least for me) has a bug where one I fill the "To" on the 3rd row, the website hangs and maxes out the CPU.

Interestingly enough, I can't reproduce the problem. Maybe it was the autocomplete going haywire?

File: openflights.css (hunk 2 above)
Comment (reedy) [reply openflights.css]: I'm not sure, but I also don't see a problem with this either...

You're working around a UI bug by setting a display order (of sorts), so setting it high it should show on top of basically everything...

Comment (reedy) [reply openflights.css]: It's also a temporary popup, not some UI element that is always on display

**Comment by reedy** [comment]
What do you want to do about merging this?

I don't think we want to just squash it all into one (as there's some clearly distinct different changes), but there's a handful of commits (mostly the fixups/prettier etc) that could be squashed into other commits

**Comment by chrisrosset** [comment]
I'll rebase a bit in a bit

**Comment by reedy** [comment]
Thanks!

**Comment by chrisrosset** [comment]
@reedy this is ready now
